### ISSUE TITLE
anaconda environment

### ISSUE THREAD

**Issue by stochasticsdrj** [jsbangsund/crystal-growth-rate-analysis#7]
Thanks jsbangsund for making this software available.
Importing or creating the environment from you .yml is not working - not a surprise since we are several years on, but is it possible to get the list of the main programs used so that I can install within my own anaconda environment please?

**Comment by jsbangsund** [comment]
What is the error you receive when trying to build from .yml? And what os are you on?

The main packages you will need are:

- numpy
- pandas
- matplotlib
- scipy
- imageio
- skimage
- palettable

Everything else should be shipped with default python. Most of these packages (except maybe skimage and palettable?) come with the default anaconda distribution. You can try to run GrowthRateAnalyzer.py and see if you get any import errors.

It is very likely that if you don't install the environment specified by the .yml, you will get a few errors or warnings due to deprecated functions in the last year or two. These should be pretty simple to fix; I'm happy to take a look at pull requests if you fix any deprecation errors.

**Comment by stochasticsdrj** [comment]
Thank you.  I will do my best to fix the deprecation errors.
OS=Ubuntu 20.04LTS
skimage installed under "scikit-image", then python -c "import skimage; print(skimage.__version__)"  is 0.19.2
The GUI for GrowthRateAnalyzer is up and running with the following comment from the terminal so far,
"QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion"

The error from the .yml is,
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - lxml==4.3.3=py37h1350720_0
  - vs2015_runtime==15.5.2=3
  - libiconv==1.15=h1df5818_7
  - m2w64-gcc-libgfortran==5.3.0=6
  - libpng==1.6.37=h2a8f88b_0
  - numpy-base==1.16.3=py37hc3f5095_0
  - wincertstore==0.2=py37_0
  - vc==14.1=h21ff451_3
  - pyrsistent==0.14.11=py37he774522_0
  - xz==5.2.4=h2fa13f4_4
  - zstd==1.3.7=h508b16e_0
  - pillow==6.0.0=py37hdc69c19_0
  - pywinpty==0.5.5=py37_1000
  - ffmpeg==4.1.3=h6538335_0
  - mkl_random==1.0.2=py37h343c172_0
  - cryptography==2.6.1=py37h7a1dbc1_0
  - yaml==0.1.7=hc54c509_2
  - pywavelets==1.0.3=py37h8c2d366_1
  - m2w64-gcc-libs-core==5.3.0=7
  - zeromq==4.3.1=h33f27b4_3
  - scikit-image==0.15.0=py37ha925a31_0
  - tornado==6.0.2=py37he774522_0
  - openssl==1.1.1=he774522_0
  - scipy==1.2.1=py37h29ff71c_0
  - pandas==0.24.2=py37ha925a31_0
  - msys2-conda-epoch==20160418=1
  - icu==58.2=ha66f8fd_1
  - freetype==2.9.1=ha9979f8_1
  - cytoolz==0.9.0.1=py37hfa6e2cd_1
  - pyqt==5.9.2=py37h6538335_2
  - libxslt==1.1.33=h579f668_0
  - markupsafe==1.1.1=py37he774522_0
  - win_inet_pton==1.1.0=py37_0
  - sip==4.19.8=py37h6538335_0
  - m2w64-gcc-libs==5.3.0=7
  - qt==5.9.7=vc14h73c81de_0
  - winpty==0.4.3=4
  - libsodium==1.0.16=h9d3ae62_0
  - mistune==0.8.4=py37he774522_0
  - intel-openmp==2019.3=203
  - mkl_fft==1.0.12=py37h14836fe_0
  - icc_rt==2019.0.0=h0cc432a_1
  - python==3.7.3=h8c8aaf0_1
  - mkl==2019.3=203
  - matplotlib==3.0.3=py37hc8f65d3_0
  - tk==8.6.8=hfa6e2cd_0
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - numpy==1.16.3=py37h19fb1c0_0
  - m2w64-gmp==6.1.0=2
  - pyyaml==5.1=py37he774522_0
  - sqlite==3.28.0=he774522_0
  - libtiff==4.0.10=hb898794_2
  - jpeg==9b=hb83a4c4_2
  - zlib==1.2.11=h62dcd97_3
  - libxml2==2.9.9=h464c3ec_0
  - pyzmq==18.0.0=py37ha925a31_0
  - cffi==1.12.3=py37h7a1dbc1_0
  - kiwisolver==1.1.0=py37ha925a31_0

**Comment by stochasticsdrj** [comment]
Stuck at the "Open Files" for the Time Series Directory, Get time from Filename (time=*s).
I used your add_timestamps.py script to do a batch conversion.
I can navigate to folder but after selecting the folder, it does not refresh the Time Series Directory.

**Comment by jsbangsund** [comment]
I had a hunch you were on Linux--I think the .yml file has windows-specific package specifications. So that explains why the .yml isn't working; at some point I should make a platform-independent .yml.

The QApplication error you see is probably also a Linux vs. windows issue, though it could also be something about the tkinter version. 

For the open files issue, could you clarify what is happening? Do you see any errors in the terminal? Are you actually selecting files or just a folder? What file format are your images?

**Comment by stochasticsdrj** [comment]
I am trying to select just a folder and it will not allow me.  I then select a group of images (first I tried jpg, then converted a couple of them to png) in that folder with the following terminal error,

Exception in Tkinter callback
Traceback (most recent call last):
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/core/imopen.py", line 146, in imopen
    return loader(request, **kwargs)
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/core/imopen.py", line 134, in loader
    return config.plugin_class(request, **kwargs)
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/config/plugins.py", line 107, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 80, in __init__
    f"`{self._format.name}`" f" can not read `{source}`."
imageio.core.request.InitializationError: `TIFF-PIL` can not read `/home/XYZ/_test/time=0.0s_IR-2000_2022-04-29 15_45_39.png`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/anaconda3/envs/growth/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "GrowthRateAnalyzer.py", line 686, in open_images_click
    self.full_images[i] = imread(f,format='tiff-pil',pilmode='L')
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/__init__.py", line 96, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/app/anaconda3/envs/growth/lib/python3.7/site-packages/imageio/core/imopen.py", line 164, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `TIFF-PIL` can not handle the given uri.

**Comment by jsbangsund** [comment]
Try to pull the latest version and see if it works for you. I added a wrapper function at the top of the file "read_image_wrapper", which you can edit if you get more errors like this that occur during image reading. see commit 6a7a63f611648e1cd3d6c3e1619d9bc8475bceab

Also, the way this is written, you have to select multiple image files, not a folder or an individual file. Though you could re-write it in your own version to select a folder if you prefer.

**Comment by stochasticsdrj** [comment]
Thanks! Will do asap.
Sorry, I forgot to mention that I did select multiple images, yes.
...bbs
